.gitattributes

I get the error message " is not a valid attribute name: .gitattributes:1"
According to http://stegriff.co.uk/upblog/gitattributes-error-is-not-a-valid-attribute-name this is because there are spaces around the equal sign.

Remove problematic spaces in gitattributes file

---

Graphic.dcm
power.dcm

Graphics.dcm and power.dcm files have tilde prepended to the component name filed. KiCad issues errors when opening these libraries (e.g. 21:06:55: Alias '~Earth_Protective' not found in library: 'D:\Mitja\Plate\Kicad_libs\official_libs\kicad-symbols\power.dcm' at line 465 offset 23)
Looking at the original files from https://github.com/KiCad/kicad-library I concluded that tilde was inserted when porting libraries.

Correct tilde in dcm files

---

Sensor_Temperature.dcm

Fix for #131. (Strangely this error is only reported by a nightly build not by the stable 4.0.6)

Fix #131: remove DS204 entry from wrong dcm file.

---

MCU_Atmel_8051.dcm
MCU_Atmel_ATMEGA.dcm
MCU_Atmel_ATTINY.dcm
MCU_Atmel_AVR.dcm
Memory_EEPROM.dcm
Memory_Flash.dcm
Sensor_Touch.dcm

all atmel documentation has been moved to microchip. The old links just point to the microchip main page, instead the documentation is now availabe on the microchip page. All links were translated from
`http://www.atmel.com/[iI]mages` to `http://ww1.microchip.com/downloads/en/DeviceDoc`.
I have tested some random datasheets from different series and they all appear to work.

update Atmel datasheet now located at microchip.com

---

Transistor_FET.dcm

Remove spaces before A,  V and ohm in two component descriptions and added package name.
------------

FET remove spaces

---

Sensor.dcm

Just a patch made by the information presented in: https://github.com/KiCad/kicad-symbols/issues/254#issuecomment-361547218
This was done by online editing (not tested though), but my knowledge about the KiCad file format is high enough to know the current file is corrupted and this patch should fix it.

Fix loading error, reported in #254

---

Device.lib

Add '*:' to the start of single letter footprint filters in device lib.

Stricter footprint filters to fix for #331

---

MCU_Atmel_ATMEGA.dcm
MCU_Atmel_ATTINY.dcm
MCU_Atmel_AVR.dcm

Some of the datasheets were 404'd or otherwise not quite right (pointing to summary, wrong device, etc).
Also filled out some missing entries. I could not find any information on the "ATmega1261" though - it is defined as an alias of the 1281 but I don't think it actually exists. Perhaps a typo that was missed when someone actually added the 1281?
------------

Fix Atmel MCU DCMs

---

.travis.yml

The default language is Ruby, which causes Travis to waste about four seconds setting up a Ruby environment we don't need every time CI is run.  This PR changes the language to the one we actually use, Python 2.7.
I suggest squash-merging this PR, as the commit history is a bit of a mess.

Set Travis to use Python 2.7

---

power.dcm

I just realized that the VCCQ symbol didn't have a description:
I added a basic one from VCC. Simple as that.
------------

Add VCCQ description

---

Amplifier_Operational.dcm

LM2904 and LM358 currently point to each others data sheets.
http://www.ti.com/lit/ds/symlink/lm358.pdf
http://www.ti.com/lit/ds/symlink/lm2904-n.pdf

Unconfuse data sheets for LM2904 and LM358

---

Device.dcm

As I noticed in #809, several manufacturers refer to resistor packs as isolated networks.  To make these symbols easier to find, this PR adds the keyword "isolated" to all the R_Pack* symbols.

Add keyword "isolated" to R_Pack* symbols

---

Graphic.dcm

Again, just making the descriptions and keywords better.
------------

Consistent descriptions and keywords for graphical/warning symbols

---

power.dcm

Just made these a little nicer looking. Fixed up capitalization & spelling etc.
------------

Consistent descriptions and keywords for power flag symbols

---

Device.dcm
sym-lib-table

The generic device library has a few spelling/capitalization errors and inconsistencies. Many of the transistor, DIAC/TRIAC, SCR, dual diode symbols etc. didn't seem descriptive enough to me, so I added the pin ordering like so:
```
D_Schottky_x2_Serial_AKC
Dual Schottky diode, anode/cathode/center
Q_NMOS_SDGD
N-MOSFET transistor, source/drain/gate, drain connected to mounting plane
LED_RCBG
RGB LED, red/cathode/blue/green
Laserdiode_P_TYPE
Laser diode with photodiode, center on pin 2, PD cathode on pin 3
```
I have not modified the symbols themselves, only the DCM descriptions and keywords.
I have a question about the keywords though: is putting "transistor" in the keywords redundant when the description also contains the word, or is there some other use for the keywords field? …

Better descriptions and keywords for Device lib

---

Mechanical.dcm
Mechanical.lib

Housing reference letter changed to N (EN 81346-2:2018)
See: http://81346.com/english/about-81346/about-81346-2-2017-edition/
Old letters MK were confuse with microphone. 
See: http://kicad-pcb.org/libraries/klc/S6.1/
Mounting hole reference letter changed to H (hardware, mountig screw etc).
See: http://kicad-pcb.org/libraries/klc/S6.1/
------------
- [-] Provide a URL to a datasheet for the symbol(s) you are contributing
- [-] An example screenshot image is very helpful
- [-] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [-] If there are matching footprint PRs, provide …

Housing reference letter changed to N (EN 81346-2:2018) and Mounting hole reference letter changed to H (symbol guidelines).

---

Interface_USB.dcm

It seems that during a descriptions update some rare characters got into a DCM file in https://github.com/KiCad/kicad-symbols/commit/9c63ffd7bac0294724b88669c2c2d837bac95504#diff-53710c242b8a37ab5f0e1e83f9809318.
I've restored those to UTF-8 hyphens so that my check scripts wouldn't crash.
Asking for @Ratfink  supervision as he made the changes originally.

Interface_USB: Fix encoding issues in DCM file

---

pspice.dcm

Replace "bibolar" with "bipolar".

Fix "bibolar" typo.

---

Diode_Laser.lib

Modify footprint filter to "D5.0mm" so it matches the LED footprint.
fixes #945

fix #945 (footprint filter to "D5.0mm")

---

Device.lib

As noticed at https://github.com/KiCad/kicad-footprints/issues/961, there are no visible pin numbers on resistor network symbols. This makes knowing which resistor in the package you've connected to difficult, which is annoying since they're interchangeable.
This PR turns on pin number visibility for the entire group of symbols.
At higher pin counts the pin number runs over the symbol body, which looks ugly, but I think having pin numbers with this caveat is better than no pin numbers. Unless there's a real reason to do more, I'd rather have this merged and then think about a better way later once we have more freedom to change symbols.
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following …

Visible pin numbers on R networks

---

Mechanical.dcm
Mechanical.lib

Analogously to the Mounting Hole, that is also a symbol in the schematics and not only a footprint.
------------

Add Fiducial as schematic symbol

---

Connector.dcm
Connector.lib

the existing `Conn_Coaxial_x2` connects the outer pins of both connectors
together, this is not the case for isolated connectors (e.g. for BNC)
It is a copy of the existing `Conn_Coaxial`, converting it into a two part unit with two identical components. As this is a generic connector there is no datasheet linked, an example component is [this](https://www.amphenolrf.com/031-6575.html). A footprint will follow in the near future.

new symbol: Conn_Coaxial_x2_Isolated

---

Switch.dcm

Just noticed this while fixing up the DIP switch generator.
------------

Add blank datasheet URLs for generic switch symbols

---

RF.lib

See: https://github.com/KiCad/kicad-footprints/pull/1325
this fixes the footprint-assignment.

RMK-3-451 and RMK-5-51: fix double underscore in PL-258 footprint

---

Simulation_SPICE.dcm

Mostly just making them sentence case, but also reworded a couple to match the Device library descriptions (eg. DIODE and OPAMP).
---

Improve SPICE library symbol descriptions

---

Device.lib

Fixes https://github.com/KiCad/kicad-symbols/issues/1554.
Just what it says on the tin. Units are not swappable in the dual and quad generic opamp symbols, but were not marked that way.
---

Prevent unit interchangeability in generic opamps

---

Amplifier_Current.dcm
Amplifier_Instrumentation.dcm
Amplifier_Operational.dcm
Analog.dcm
Analog_ADC.dcm
Analog_DAC.dcm
Battery_Management.dcm
Comparator.dcm
Driver_FET.dcm
Driver_LED.dcm
Interface.dcm
Interface_CAN_LIN.dcm
Interface_UART.dcm
Power_Management.dcm
RF_Mixer.dcm
Reference_Voltage.dcm
Regulator_Controller.dcm
Regulator_Linear.dcm
Regulator_SwitchedCapacitor.dcm
Regulator_Switching.dcm
Sensor.dcm
Sensor_Temperature.dcm

Analog bought linear some time ago, thankfully they maintained all
datasheets and have easy to generate URLs. For all datasheet URLs the
HEAD was downloaded and checked for a "200 OK" status code. Those which
had errors (only a couple) were fixed manually.
This fixes issue #1547.

convert linear.com links to analog.com

---

74xx.dcm
Amplifier_Audio.dcm
Amplifier_Current.dcm
Amplifier_Instrumentation.dcm
Amplifier_Operational.dcm
Analog_DAC.dcm
Battery_Management.dcm
Diode_Laser.dcm
Display_Character.dcm
Driver_FET.dcm
Interface.dcm
Isolator.dcm
Logic_LevelTranslator.dcm
Reference_Voltage.dcm
Regulator_Linear.dcm
Regulator_SwitchedCapacitor.dcm
Regulator_Switching.dcm
Relay.dcm
Relay_SolidState.dcm
Timer.dcm
Transistor_FET.dcm
Triac_Thyristor.dcm

- Remove spaces in front of "A" and "V", as well as some other inconsistencies as per #1615 
- Fix incorrect `Id` and `Vds` ratings for Si1442DH (they were swapped) as per [Datasheet](https://www.vishay.com/docs/63772/si1442dh.pdf)
- Add `0.2A Id` rating for 2N7000 as per [Wikipedia](https://en.wikipedia.org/wiki/2N7000) and [Datasheet](https://www.onsemi.com/pub/Collateral/2N7000-D.PDF)
---

Make component descriptions consistent

---

power.dcm

All power symbols where reffered to as power flags in their description. I made it clear that they create global labels and added a special descritpion to the PWR_FLAG symbol to tell users that this one is to be used to tell ERC where power comes from.

Clearer descriptions for power symbols

---

Amplifier_Audio.dcm

THAT2181: Description typo
Description is copied from THAT2180 which is pre-trimmed. This is not the case
for THAT2181.
http://www.thatcorp.com/datashts/THAT_2181-Series_Datasheet.pdf
---

THAT2181: Description typo

---

pspice.dcm

Fix reference to 'Capacitor' in 'Inductor' description.

Fix 'Inductor' description.

---

Amplifier_Audio.dcm

* Update DS link
Fixes #2062 
DS http://www.ti.com/lit/ds/symlink/lm4810.pdf
---

Fix LM4810

---

Oscillator.dcm
RF.dcm
RF_Switch.dcm
Transformer.dcm

As pointed out by @aewallin Mini-Circuits moved their datasheets from ww2.minicircuits.com to www.minicircuits.com. This fixes the existing symbols in the library

fix minicircuits ww2 library links

---

MCU_Microchip_SAME.dcm

MCU_Microchip_SAME now use one datasheet for the SAM E70/S70/V70/V71 family (https://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en589960), and one for the SAM D5x/E5x family (https://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en599585).

Update datasheet links for MCU_Microchip_SAME parts

---

Transformer.dcm

As noted in #2264, Minicircuits RF tranformer descriptions did not match datasheet values.
Datasheet links:
- https://www.minicircuits.com/pdfs/ADT1-1WT-1+.pdf
- https://www.minicircuits.com/pdfs/ADT1.5-1+.pdf
- https://www.minicircuits.com/pdfs/ADT2-1T+.pdf
- https://www.minicircuits.com/pdfs/ADT2-1T-1P+.pdf
- https://www.minicircuits.com/pdfs/ADT3-1T+.pdf
- https://www.minicircuits.com/pdfs/ADT3-1T-75+.pdf
- https://www.minicircuits.com/pdfs/ADT4-1T+.pdf
- https://www.minicircuits.com/pdfs/ADT4-1WT+.pdf
- https://www.minicircuits.com/pdfs/ADT9-1T+.pdf
- https://www.minicircuits.com/pdfs/ADT16-1T+.pdf
---
Checklist:

Fix ADTxx descriptions

---

Mechanical.lib

I didn't catch this when I submitted https://github.com/KiCad/kicad-symbols/pull/2355, but the heatsink FP filters specified anything in the heatsink library. That is unlike the other generic symbols (resistors are `R_*`, for examples) and also all heatsink in that library start with `Heatsink_`. So I updated the FP filter to match footprints names rather than the library name.
---

Update heatsink FP filters

---

Device.lib
Jumper.lib

Both solder jumpers and non-solder jumpers had FP filters for solder jumpers. I removed the solder jumper FP filter for the latter and added a non-solder jumper FP filter (of which we have none right now) and also a FP filter for testpoints with multiple pads which would work for jumpers.
We could add jumper footprints the same or similar to the testpoint footprints we have now, but I wasn't sure if that would be accepted having the same footprints twice.
---
- A new fitting footprint must be submitted if the library does not yet …

Updated jumper FP filters

---

Connector.dcm
Connector.lib

Added a really small testpoint that's super useful for compact schematics, or just sprinkling on pins that would normally be NC.
An example of the symbol being used, once on top of a wire junction and once not:
---

Add TestPoint_Small

---

Simulation_SPICE.lib

As mentioned at https://forum.kicad.info/t/where-is-the-right-place-to-get-in-touch-with-a-kicad-dev/20738/17. Makes the DIODE symbol default to a diode and the OPAMP symbol default to an opamp with a subcircuit implementation. The actual simulation model is still left up to the user.
---

Fix simulation DIODE and OPAMP primitive types

---

Reference_Voltage.dcm

Components:
> REF3212AMDBVREP
> REF3220AMDBVREP
> REF3225AMDBVREP
> REF3230AMDBVREP
> REF3233AMDBVREP
> REF3240AMDBVREP
All had "Prevision" as keyword instead of "Precision". 
Can be found in 'kicad-symbols' with ripgrep:
`rg -g '*.dcm' -e 'Prevision' --context 2`
Not a big deal, but I randomly stumbled upon this.
Sample [datasheet](https://www.ti.com/lit/ds/symlink/ref3212-ep.pdf). However, they are not recommended for new design.

Update typo in Voltage_Reference.dcm: "Prevision" -> "Precision"

---

Device.dcm
Device.lib

[Motivated by these slide potentiometers that have mounting pins.](https://github.com/KiCad/kicad-footprints/pull/920)
I suspect that what I have here isn't quite right, but I wasn't really sure what a potentiometer with a mounting pin should look like, so I could use some feedback.
There are a bunch of KLC warnings, but they seem to have been inherited from the original `R_POT` symbol that I based this on.
------------

Add symbol R_POT_MountingPin.

---

4xxx.dcm
Analog_Switch.dcm
Driver_FET.dcm
Isolator.dcm
Regulator_Linear.dcm
Regulator_Switching.dcm
Relay_SolidState.dcm
Transistor_BJT.dcm
Transistor_FET.dcm

this is part of issue-2895 : fairechildsemi.com links for datasheet are leading to a page that is not a pdf file
I've replaced most of them with new onsemi.com links, but some others couldn't be found so I've used links from digikey, farnell or ti.

issue-2895 correcting fairchildsemi.com dead links

---

Regulator_Linear.dcm

The datasheet pointed to the -n variant which is a different part.

Fix datasheets of LP2951-***

---

MCU_Microchip_ATtiny.dcm
Memory_EEPROM.dcm
Memory_Flash.dcm
obsolete/MCU_Microchip_ATtiny.dcm
obsolete/MCU_Microchip_AVR.dcm

https://github.com/KiCad/kicad-symbols/pull/1587 changed the default packages on symbols from SOIJ to SOIC, but the descriptions didn't get updated. This was caught by @fauxpark at https://github.com/KiCad/kicad-symbols/pull/1587#issuecomment-700740888.
Only descriptions are changed. It's a minor thing, but that also means it should be easy to review and commit.
I threw in a fix for the description of `M25PX32-VMP` too since it was ugly and I was there.
---
In preparation for the KiCad v6 release this repository will be locked down on Sept 1, 2020. No new pull requests will be accepted. Existing pull requests can be worked on until Oct 1, 2020. Changes breaking v5.1 compatibility can be merged starting Sept 1, 2020.
On Oct 1, 2020 this repository, including issues and pull requests, will …

Correct SOIJ-8 in description to SOIC-8W
