KiCad/kicad-symbols

TODO.md, sym-lib-table
- elec-unifil contains old strange components
- will not transfer to new lib
=> Updated TODO and sym-lib-table

Connector_Generic.lib
=> Fix Conn_2Rows-nnPins lib->dcm connection.

Regulator_Switching.dcm
Add package name to LM5022MM in symbol description
Datasheet: http://www.ti.com/lit/ds/symlink/lm5022.pdf
------------
=> Add package name to LM5022MM

Sensor.lib
=> Fix footprint field for Bosch sensors

Mechanical.dcm, Mechanical.lib
*Replace this line with your commit message! Please provide a description of your pull request*
------------
=> Mechanical: Rename mounting holes to be consistent and update FPFilters

Connector.dcm, Connector.lib
*Replace this line with your commit message! Please provide a description of your pull request*
------------
=> Connector: Rename Test_Point to TestPoint

Transformer.lib
rename footprints matching [this PR](https://github.com/KiCad/kicad-footprints/pull/594).
------------
=> move footprint for symbols w/ Mini-Circuits CDxxx

Device.lib
Does just what it says on the tin...
------------
=> Change ferrite bead ref des to FB

Sensor_Magnetic.dcm
Update datasheet link 
Added package name on description
This update was part of closed PR: https://github.com/KiCad/kicad-symbols/pull/669
------------
=> [Sensor Magnetic] Update datasheet link

Transistor_IGBT.lib, Triac_Thyristor.lib
See https://github.com/KiCad/kicad-symbols/pull/1181
No open PRs for those libs
=> Triac and IGBT: Update to latest file version

Interface_Telecom.dcm
only update datasheet of FX614
------------
=> Interface_Telecom: Update datasheet of FX614

4xxx.dcm, 74xx.dcm, Diode.dcm, Power_Protection.dcm, Timer_RTC.dcm, Transistor_BJT.dcm, Triac_Thyristor.dcm, Video.dcm
A number of URLs no longer resolve after the NXP to Nexperia
change. Fix them.
=> Fix some invalid NXP URLs

Regulator_Linear.dcm
fixes #1512 and other mcp1700 parts using the old link
=> corrected mcp1700 datasheet link

Sensor_Voltage.dcm
=> Fix LEM LV25 doc link

Sensor_Temperature.dcm
=> Datasheet MCP9700

Sensor.dcm
I've been gone for a while (glad to be back)! Modified the descriptions/keywords for:
- BME280
- BME680
- AS3935
=> Improve some sensor keywords and descriptions

Diode.dcm
It's 200V not 20V from the datasheet.
=> Fix 1N4003 description.

RF_GSM.dcm
=> Fix datasheet of SIM7020x

4xxx.dcm
fix bad url line
*Replace this line with your commit message! Please provide a description of your pull request*
---
---
Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or …
=> Fix a bad URL line

README.md
I would be glad if a native speaking person could double-check the text. Wording/Syntax/Typos. Thanks.
=> Add deprecation warning to README.md
